language: generic

matrix:
  include:
  - os: linux
    sudo: required
    env: TOXENV=py36
  - os: linux
    sudo: required
    env: TOXENV=py37

cache:
  directories:
    - $HOME/miniconda

install:
  - if [[ ! -e "$HOME/miniconda/bin/conda" ]]; then "./.ci_scripts/install_miniconda.sh"; fi
  - export PATH=$HOME/miniconda/bin:$PATH
  - source activate test-env
  - conda update --all
  - conda clean --all

script:
  - pip install --no-deps -e .
  - flake8 ngmix
  - pytest -v --cov=ngmix ngmix
  # make sure to uninstall so that we do not invalidate the build cache
  - pip uninstall ngmix -y
  - rm -rf ${HOME}/miniconda/envs/test-env/lib/python*/site-packages/ngmix*
